builders:
  circle_flags|assetsToCache:
    import: "package:flag_builder/builders.dart"
    builder_factories: ["assetsToCache"]
    build_extensions: { "*.svg": [".part.txt"] }
    auto_apply: root_package
    build_to: cache
    runs_before:
      - circle_flags|combineFlagFile

  circle_flags|combineFlagFile:
    import: "package:flag_builder/builders.dart"
    builder_factories: ["combineFlagFile"]
    build_extensions: { r'$package$': ["lib/src/flag.dart"] }
    auto_apply: root_package
    build_to: source
    required_inputs:
      - .dart_tool/build/generated/circle_flags/assets/svg/*.part.txt