name: circle_flags
description: A collection of roundd flags
version: 5.0.1
repository: https://github.com/cedvdb/flutter_circle_flags

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  dart_countries: ^3.0.3
  phone_numbers_parser: any

flutter:
  assets:
    - assets/svg/
